server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: mutant
          uri: lb://mutant
          predicates:
            - Path=/mutant/**
          - id: stats
          uri: lb://stats
          predicates:
            - Path=/stats/**
